sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  oss:
    endpoint: oss-us-west-1.aliyuncs.com
    access-key-id: LTAI5tS3tdiAosuGrDe2HjGY
    access-key-secret: 4ygr927SkCiJNkhCPXipnfbyM5gjOi
    bucket-name: web-tlias-yuheng

  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10


  wechat:
    appid: wx9557ca2419dc51f0
    secret: 704f54c1d89d4747e9a6ec26fd252234
