sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  oss:
    endpoint: oss-us-west-1.aliyuncs.com
    access-key-id: LTAI5tS3tdiAosuGrDe2HjGY
    access-key-secret: 4ygr927SkCiJNkhCPXipnfbyM5gjOi
    bucket-name: web-tlias-yuheng
