sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  oss:
    endpoint: oss-us-west-1.aliyuncs.com
    access-key-id: LTAI5tS3tdiAosuGrDe2HjGY
    access-key-secret: 4ygr927SkCiJNkhCPXipnfbyM5gjOi
    bucket-name: web-tlias-yuheng

  redis:
    host: localhost
    port: 6379
    password: 1234
    database: 10


  wechat:
    appid: wx9557ca2419dc51f0
    secret: 704f54c1d89d4747e9a6ec26fd252234
    mchid: 1561414331
    mchSerialNo: 4B383DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\pay\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\pay\wechatpay_166096F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://5b133f78.r20.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://5b133f78.r20.cpolar.top/notify/refundSuccess
